server_addr = "127.0.0.1:8080"
update_interval = 60

nodes = [
    "https://1rpc.io/eth",
    "https://eth.drpc.org",
    "https://eth.llamarpc.com",
    "https://ethereum.blockpi.network/v1/rpc/public",
    "https://ethereum.blockpi.network/v1/rpc/public",
]
